- name: variables
  hosts: local
  connection: local
  vars: # PLAY Level variables -Parent level, global variables
    COURSE: "DevOPS AWS"
    DURATION: 120
    TRAINER: Sivakumar
  tasks: 
  - name: print the variables
    vars:   # task level variables, accessiable only with in the tasks. Task variables can override play lvel variables
      COURSE: "java with AWS"
    ansible.builtin.debug:
      msg: "Course is {{COURSE}} , duration is {{DURATION}} hours, Trainer is {{TRAINER}}"
      
  - name: print the variables1
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

  # tasks:
  # - name: print the variables1
  #   vars:
  #     COURSE: :"azure"
  #   ansible.builtin.debug:
  #     msg: "Course is {{COURSE}} , duration is {{DURATION}} hours, Trainer is {{TRAINER}}"      
